version: '3.9'

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGODB_URI: mongodb://mongo:27017/student-feedback
      JWT_SECRET: change_me_access
      JWT_EXPIRES_IN: 15m
      REFRESH_JWT_SECRET: change_me_refresh
      REFRESH_JWT_EXPIRES_IN: 7d
      CLIENT_URL: http://localhost:5173
    ports:
      - '4000:4000'
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  mongo_data:
